spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

fetching:
  schedule: 0 0 4 * * *

jwt:
  key: "8CHJbNmJNTyB4sAgIB+GoZYpgEOswosxM5QxcFeEsR/0o2++eWAKAuMIocjx9eiy\
      a2XbOVu7KcxrFBNEtprAGBCvtznQrugTfW742c6r9C3y9oGMY2shfrBePVhhZjpq\
      VezvMKnDeC0k8iFk8qzStzJyPE1qMhtagxw1IXCzrelRERbW8HU+BXUzk8i2DY57\
      M/WfKJW4jOh4uFeUYJ4P1N1yq0XX+bjD3v/D+dtMYc9bDMnODH/CM4gGtsnP3nRO\
      y7rYUo8rMo+s9eeE7sZj8tHnStoGXR6VMpqFNBC1OCXUxD6a6075yUBXqqchHBMD\
      Bcte3vTlx5eLTxYyzJtWz88DxWfNqKyGlUce0RyZ7i8K47QlPbNFrdAXNKHwGL8n\
      cCFdG7c3OfXhe3p2NCQ66Q5DOPZZrepRVVVyVd1vksHwVNKsPo+XYSKQUh9ZfyGR\
      yWUetgvO6WI3dkFisFESueO1Txg+waOJ4CJPY0EtDJBMJiNOSFjkwwWiRvy6vTYX\
      8ExWA3c3ww9D9mehwoCDTa7C7OtRFxKZ8XWAzr0zBs9OEgVt71ch02tOe44UfQLF\
      liakYNBBN4YtdrhFJZegTqRWU4cKqD8z3gJfnv+Ukl1f5CGa5ctiwg3nEKcEL+k2\
      XB/9DiRwRhfI67zqMrSAs/CQHdo5oVv48nsJRzU0rSdInD6dG8FrP3hc/N9Yb1UK\
      xvZSbqjUq1R2OAcVjTsxJothgfpy6g/0HKMITG2/mAN6PWq8UIuJay7tRYRDRFKM\
      zOg5NGQjRwb8NTzGxv8qH5cCiHJFCZyHce347qcMomNTAVBcUYN+S6aiIgJW+oTM\
      Mg0hTmaF5hNZkZ8+BwrYdbM7f0iDfnA5mikjQrTZrjRi7gv4JA2lgJ5mWoyDhJIe\
      sk23xpAzsEOIwzIAVYhb/EcuoLza9V1rcD1Sha1N5H6uv6ZoC/UAK/PgaTt96xjp\
      XaAa4P/RPiMT9gJeaoWT0KjfKn7S9q98Y0xY3g9hoHmRKMEH+df2IR4RVtjeq19S\
      ntsXLwmInWU+LvAYmVAW5i7DuZx0LLU+0QBqCpKAGlaTGnh4E4ZkhAVdA9AnF7Yq\
      woZpOupDLfpesrsjeCpkZ+/AlLkqpbljX/17814zGoOUVTYC5T/mIWMm3UJrAAw+\
      GnpaLoVbRyWmqpLoLnleIQbaq9RiersTGC7WLIod4V5trz5yVTMjxTpH4xbjZ61E\
      5yBnqj3i+A96o4B/ZwYrw/6nG+QyquJOjBkHDwf6qPQQb2CRJkyA1yWob9NAq/GF\
      gMRT0sxLyz9tpMKp4r+4e8dmnmt5EyDkNDFXhohbhPS6XPrEarehJFI/FAG3VJjx\
      fINw/chOzfKBt8Gl3kjEXw="
